title: SDO by Skipline
remote_theme: just-the-docs/just-the-docs
permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
    
heading_anchors: true
enable_copy_code_button: true
# Disable blog features
