---
- name: Change sysctl config
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728
      vm.max_map_count = 1000000
      fs.nr_open = 1000000
  notify: Reload sysctl

- name: Set CPU governor to performance
  lineinfile:
    path: /etc/default/cpufrequtils
    line: 'GOVERNOR="performance"'
    create: yes

- name: Set scaling governor to performance for all CPUs
  shell: echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  when: ansible_processor_cores is defined and ansible_processor_cores | int > 0

- name: Change systemd default limit for open files
  ansible.builtin.ini_file:
    path: /etc/systemd/system.conf
    section: Manager
    option: DefaultLimitNOFILE
    value: "1000000"
  notify: Reload systemd daemon