---
- name: Get minimum required version
  uri:
    url: "https://api.solana.org/api/epoch/required_versions?cluster={{ group_names[0] }}"
    return_content: true
  register: minimum_required_version

- set_fact:
    agave_version: "{{ minimum_required_version.json.data[0].agave_min_version }}"

- set_fact:
    firedancer_version: "{{ minimum_required_version.json.data[0].firedancer_min_version }}"