---
- name: Get github repo for Jito
  become: false
  git:
    repo: https://github.com/jito-foundation/jito-solana.git
    dest: "/home/{{ sdo_user }}/jito"
    version: "{{ jito_version }}"
    force: true
    recursive: yes

- name: Build Jito (Will take a while. Be patient)
  shell: sudo -iu {{ sdo_user }} bash -c "cd /home/{{ sdo_user }}/jito/scripts && ./cargo-install-all.sh ."
  args:
    creates: "/home/{{ sdo_user }}/jito/scripts/bin/agave-validator"
  

- name: Add Jito to PATH
  become: false
  lineinfile:
    path: /home/{{ sdo_user }}/.bashrc
    line: 'export PATH=/home/{{ sdo_user }}/jito/scripts/bin:$PATH'
    state: present

- name: Copy validator startup script
  template:
    src: validator-startup.sh.j2
    dest: /home/{{ sdo_user }}/validator-startup.sh
    mode: '0755'
    owner: "{{ sdo_user }}"
    group: "{{ sdo_user }}"
  when: validator_type == 'Jito'