---
- name: Get latest Firedancer version
  uri:
    url: "https://api.github.com/repos/firedancer-io/firedancer/releases?per_page=10"
    return_content: true
  register: firedancer_version_response

- set_fact:
    firedancer_version: >-
      {{
        (firedancer_version_response.json
          | selectattr('name', 'search', group_names[0], ignorecase=True)
          | map(attribute='tag_name')
          | list | first)
      }}

- name: Get github repo for Firedancer
  become: false
  git:
    repo: https://github.com/firedancer-io/firedancer.git
    dest: "/home/{{ sdo_user }}/firedancer"
    version: "{{ firedancer_version }}"
    force: true

- name: Install dependencies to build Firedancer
  become: false
  shell: yes y | ./deps.sh
  args:
    chdir: "/home/{{ sdo_user }}/firedancer"

- name: Build fdctl(Will take a while. Be patient)
  become: false
  shell: sudo -iu {{ sdo_user}} bash -c "cd /home/{{ sdo_user }}/firedancer && make -j fdctl"

- name: Build solana (Will take a while. Be patient)
  become: false
  shell: sudo -iu {{ sdo_user}} bash -c "cd /home/{{ sdo_user }}/firedancer && make -j solana"

- name: Copy Firedancer config file
  template:
    src: firedancer-config.toml.j2
    dest: "/home/{{ sdo_user }}/fd-config.toml"
    mode: '0644'
    owner: "{{ sdo_user }}"
    group: "{{ sdo_user }}"