---
- name: Create user {{ sdo_user }}
  user:
    name: "{{ sdo_user }}"
    comment: "SDO User for Validator Operations"
    groups: sudo
    shell: /bin/bash
    generate_ssh_key: true
    state: present

- name: Add {{ sdo_user }} to sudoers with NOPASSWD
  lineinfile:
    path: "/etc/sudoers.d/{{sdo_user}}-nopasswd"
    state: present
    line: "{{sdo_user}} ALL=(ALL) NOPASSWD:ALL"
    create: yes
    validate: 'visudo -cf %s'

- name: Add ssh public key for sdo user
  authorized_key:
    user: sdo
    state: present
    key: "{{ lookup('file', ansible_ssh_private_key_file ~ '.pub') }}"
  when: ansible_ssh_private_key_file is defined

- name: Create or add existing ssh key
  block:
    - name: Find existing SSH key
      become: false
      delegate_to: localhost
      stat:
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
      register: ssh_key

    - name: Create SSH key if not found
      become: false
      delegate_to: localhost
      openssh_keypair:
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
      when: ssh_key.stat.exists == false

    - name: Add SSH public key to authorized_keys
      authorized_key:
        user: "{{ sdo_user }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') ~ '/.ssh/id_rsa.pub') }}"
  when: ansible_ssh_private_key_file is not defined